### ISSUE TITLE
Checkbox "Yes! I will use DataPLANT." has no effect 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/dataplan#10]
Unfortunately, checking the box  
> Yes! I will use [DataPLANT](https://nfdi4plants.github.io/).

did not update my DMP accordingly. None of the `#if$_DATAPLANT` statements made it into my DMP, meaning I have to add them manually now :(

**Comment by Brilator** [comment]
Also the "Do you need visualization in the project?" option just resets my previous selections.

**Comment by xiaoranzhou** [comment]
Are you using Safari on a Mac? For me the Chrome and Firefox works both fine. I only tested it on the safari of my ipad. If you can provide your browser, OS version and saved JSON file, that will be helpful to debug. I can not debug if I can not recreate your bugs.

**Comment by xiaoranzhou** [comment]
> Unfortunately, checking the box
> 
> > Yes! I will use [DataPLANT](https://nfdi4plants.github.io/).
> 
> did not update my DMP accordingly. None of the `#if$_DATAPLANT` statements made it into my DMP, meaning I have to add them manually now :(

What do you mean by adding them manually?

**Comment by Brilator** [comment]
I filled out the dataplan (right panel), downloaded (copied) the text to a word document, since I cannot edit the text blocks in the browser. 
Now, I've checked the index.html for every time `#if$_DATAPLANT` was used in the DFG template and add these blocks to my DMP doc...

**Comment by Brilator** [comment]
> Are you using Safari on a Mac? For me the Chrome and Firefox works both fine. I only tested it on the safari of my ipad. If you can provide your browser, OS version and saved JSON file, that will be helpful to debug. I can not debug if I can not recreate your bugs.

Yes. Works in Firefox. Cannot confirm that it works on iPad (did not on mine, iOS 15.6). 
Does not work in macOS 12.5 / Safari 15.6. 

Maybe add a warning to the top.

**Comment by xiaoranzhou** [comment]
> > Are you using Safari on a Mac? For me the Chrome and Firefox works both fine. I only tested it on the safari of my ipad. If you can provide your browser, OS version and saved JSON file, that will be helpful to debug. I can not debug if I can not recreate your bugs.
> 
> Yes. Works in Firefox. Cannot confirm that it works on iPad (did not on mine, iOS 15.6). Does not work in macOS 12.5 / Safari 15.6.
> 
> Maybe add a warning to the top.

I think it should work. Are you using some plugins which will modify your webpage? You can test it in Incognito page. The function I use was all promised to function in the new Safari.... I can try to debug them in a VM but it take some time.

**Comment by xiaoranzhou** [comment]
> I filled out the dataplan (right panel), downloaded (copied) the text to a word document, since I cannot edit the text blocks in the browser. Now, I've checked the index.html for every time `#if$_DATAPLANT` was used in the DFG template and add these blocks to my DMP doc...

You can actually try the "user defined template" in "Template" menu. There you could edit every thing just like before.

**Comment by xiaoranzhou** [comment]
@Brilator 
Hey Dominik, I recreated the bug and fixed it. I can push it now if it is OK for you. Otherwise you can also try it here: [link](xrzhou.com/g)

**Comment by Brilator** [comment]
> @Brilator
> Hey Dominik, I recreated the bug and fixed it. I can push it now if it is OK for you. Otherwise you can also try it here: [link](xrzhou.com/g)

Yes, works in Safari now. (the link btw doesn't).
