### ISSUE TITLE
What's "Visualization"? 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/dataplan#2]
What is meant by? 

> 5. Do you need visualization in the project?

**Comment by xiaoranzhou** [comment]
visualization is visualization. Das heißt Visualisierung auf deutsch ;D
Most of the confusions should be solved by tooltips or hover text.

**Comment by Brilator** [comment]
Thanks, I know what the word means :). 
Just from perspective of a non-FAIR / RDM / data expert, what does "Do you need visualization in the project?" imply? Is the DataPLAN going to draw my project / DMP outline?

**Comment by xiaoranzhou** [comment]
It could be a future feature. Currently it is only used to assign this task to DataPLANT or another standardized  data management process.
![image](https://user-images.githubusercontent.com/29843510/187229270-07677f9b-66fc-43e8-8c5a-04f2b892382d.png)
You can test the outcome.
