### ISSUE TITLE
Change some language-related issues

### ISSUE THREAD

**Issue by StellaEggels** [nfdi4plants/dataplan#23]
There are some expressions and other language related things I noticed, that I would change:

1.	In front of every “projectname” there is a “the”. Maybe delete it, I think it is uncommon to use a “the” in front of a project name
2.	The sentence under 1) “The aim of this document….”, I would split into two sentences.
3.	Check the use of “.” to end a sentence. Sometimes it is missing, sometimes there is a comma instead, sometimes there are two dots and sometimes there are spaces in front.
4.  2.2) “Here, the examplename will build on the advanced ontologies developed in DataPLANT.” > change “developed” to “integrated” or something similar, because most ontologies that used in DataPLANT weren't developed in DataPLANT.
5. 2.3) “The data officer will ultimately decides...”, it should be “decide”.
6. 2.4) the first of the following sentences is missing a verb, for the second one I’m not sure what you are meaning to say.: “All partners holding confidential project data to use secure platforms with automatic backups and offsite secure copies. DataHUB and ARCs have been generated in DataPLANT, data security will be imposed.”

**Comment by xiaoranzhou** [comment]
Done, Thanks
