### ISSUE TITLE
Improve documentation / wiki 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/dataplan#3]
This project could need a bit more documentation. So, apart from the tutorial (this is how), maybe share some documentation on the individual sections, why the questions might be asked (e.g. from DFG) and more importantly how my selection / edited data in the sidebar affects / changes the DMP (although this could eventually be read from the DMP once finished).

**Comment by Brilator** [comment]
Some examples:

> Where will you submit your data as endpoints?

What is an "endpoint" and how do I know which one is important for my data? 

> Are there any standards that are relevant for you?

What are standards? What is MIAPPE, MINSEQE, Dublin Core? How do I find out wether these are relevant for my project?  

> When will you make your data public?
> Will you publish your data early?

When is early?

**Comment by Brilator** [comment]
#2 
#1

**Comment by xiaoranzhou** [comment]
> This project could need a bit more documentation. So, apart from the tutorial (this is how), maybe share some documentation on the individual sections, why the questions might be asked (e.g. from DFG) and more importantly how my selection / edited data in the sidebar affects / changes the DMP (although this could eventually be read from the DMP once finished).

Programming documentation is absolutely a TODO. The others were written in a manuscript draft.

**Comment by AngelaKranz** [comment]
This issue is still open.
@xiaoranzhou: Is this still being worked on?

**Comment by xiaoranzhou** [comment]
This can be closed in my point of view because we have knowledge base articles now. https://www.nfdi4plants.de/nfdi4plants.knowledgebase/docs/implementation/DataPLAN.html

**Comment by xiaoranzhou** [comment]
I will close this one as the knowledgebase article has been online for a while.
