### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by AngelaKranz** [nfdi4plants/dataplan#31]
Readme should be updated and easier to understand for users

**Comment by xiaoranzhou** [comment]
Thank you very much for your feedback. I have created a new version here:
https://github.com/nfdi4plants/dataplan/pull/32

**Comment by xiaoranzhou** [comment]
# DataPLAN

## Introduction
**DataPLAN** is a user-friendly, serverless Data Management Plan (DMP) generator developed by DataPLANT. It simplifies the creation of DMPs for various projects, including Horizon Europe, H2020, and DFG. This tool can be easily understood by watching this quick [two-minute video](https://www.youtube.com/watch?v=T40Kmah1RTY).

[![Watch the video on YouTube](https://img.youtube.com/vi/T40Kmah1RTY/0.jpg)](https://www.youtube.com/watch?v=T40Kmah1RTY)

## Usage
### Online
- Visit [plan.nfdi4plants.org](https://plan.nfdi4plants.org) to use DataPLAN directly in your browser.

### Offline
1. Download the [zip file](https://github.com/nfdi4plants/dataplan/archive/refs/heads/main.zip).
2. Unzip the file.
3. Open `index.html` in your browser.

## Saving Your Answers
- **Automatic Storage**: Your answers are automatically saved in your browser.
- **Cross-Device Use**: Export and import your answers as JSON files to transfer between browsers or devices.

## Folder Structure
- `/js/`: JavaScript files for functionality and styling.
- `/css/`: Stylesheets for layout and design.
- `/DMPDocs/`: Templates for DMP documents.
- `index.html`: The main file that runs the application.

## Publication
DataPLAN is featured as an issue cover in the journal *Data*:  
[![DataPLAN publication](https://nfdi4plants.github.io/dataplan/images/cover.webp)](https://www.mdpi.com/2306-5729/8/11/159)

## License
This project is licensed under the [GPL-3.0 License](https://www.gnu.org/licenses/gpl-3.0.en.html).

## Libraries and Tools
DataPLAN leverages several open-source projects:
- **UI**: [Bootstrap 5](https://getbootstrap.com/) and [bs5-intro-tour](https://github.com/yaras6/bs5-intro-tour)
- **Visualization**: [d3.js](https://d3js.org/) and [d3-cloud](https://github.com/jasondavies/d3-cloud)
- **File Handling**: [FileSaver.js](https://github.com/eligrey/FileSaver.js/)

Thanks to these communities for their contributions!

**Comment by AngelaKranz** [comment]
Thanks, I will correct and improve it via an additional pull request
