### ISSUE TITLE
Question 4.4 does not make any sense...

### ISSUE THREAD

**Issue by AngelaKranz** [nfdi4plants/dataplan#39]

**Comment by xiaoranzhou** [comment]
Question 4.4 is:
4.4 Will you follow national standards or archived in national infrastructures?
German NFDI
French INRAe
Europe EOSC

I added this option based on some suggestions:

```
Country conditions
Transcriptomics data and gene sequence data will be also made available upon publication via the standards ENA/SRA, metabolite data in e.g. Metabolights (and/or Nationwide repositories like the German NFDI the French INRAe),

Should need country selections even though it is not strict.
```
I think this might be useful in the future? I can also make this question invisible.

**Comment by xiaoranzhou** [comment]
Rephrase the question

**Comment by xiaoranzhou** [comment]
Draft answer: Which national, funder, sectorial, or departmental data management procedures do you follow, and which national research data infrastructure do you use?

**Comment by AngelaKranz** [comment]
Sounds better
