### ISSUE TITLE
Improve intro

### ISSUE THREAD

**Issue by AngelaKranz** [nfdi4plants/dataplan#40]
There are several grammar issues:

![image](https://github.com/user-attachments/assets/d9ba3cc5-94e9-4322-908f-ff964e1ad78a)

Welcome to DataPLAN!
The work is published **in** Data.

![image](https://github.com/user-attachments/assets/b2b52547-d4f3-4b26-821f-d96fa7b95090)

The questionnaire **has** five sections.

![image](https://github.com/user-attachments/assets/b69e856f-609c-4e35-b453-9ee9cea40c4f)

The links are just initializing a switching in the background. Links to actual examples files would be helpful. Also, you are just mentioning the DFG Template.

**Comment by xiaoranzhou** [comment]
Thanks for your suggestion. I have update the tool.
