### ISSUE TITLE
Enable easier user contribution

### ISSUE THREAD

**Issue by AngelaKranz** [nfdi4plants/dataplan#45]
Users should easily be able to suggest improvements or corrections to the DMP through an 'Edit' button, which automatically generates a pull request, similar to the workflow used for the Knowledge Base.

**Comment by xiaoranzhou** [comment]
Thanks for your suggestion, I have updated such edit template buttion: 
![image](https://github.com/user-attachments/assets/183cfb15-1e20-4a2d-8fa7-eaed4ac25c35)
