### ISSUE TITLE
Minor: Format / numbering level1 headings 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/dataplan#5]
> ### 1 . Data description
> ### 2 Documentation and data quality
> ### 3. Storage and technical archiving the project
> ### 4. Legal obligations and conditions
> ### 5. Data exchange and long-term data accessibility
> ### 6. Responsibilities and resources
> ### 3 Annexes

- rm space in `1 . Data...`
- `2. Documentation...`
- 3 Annexes -> 7 Annexes?

**Comment by xiaoranzhou** [comment]
fixed
