### ISSUE TITLE
Repetitive elements in DFG template 1.4 and 2.

### ISSUE THREAD

**Issue by StellaEggels** [nfdi4plants/dataplan#50]
The response to 1.4 starts with two sentences that have the same meaning: 
We foresee that the following data about Example Topic will be collected and generated at the very least: test will collect and/or generate the following types of raw data: 

And in the response to 2. there is also a repetitive part and grammar issue:
 ...will rely on community standards plus additional recommendations applicable in the plant science, such as the The following metadata/ minimum informatin standards will be used to collect metadata

And you can see in the copied text above there is a typo in "information".

**Comment by StellaEggels** [comment]
Wouldn't it be enough to only keep one of those sentences?

**Comment by xiaoranzhou** [comment]
Yes, I will only keep the last sentence: "As part of $_PROJECTNAME, the following types of data will be gathered and/or produced. "
