### ISSUE TITLE
Improve sentence under 1.3 (DFG)

### ISSUE THREAD

**Issue by StellaEggels** [nfdi4plants/dataplan#52]
I think the first part of the sentence below might not work for many topics and the second part does not work gramatically:

It is also important to include existing data sets on the expression and metabolic behaviour of Example Topic, but of course, also on existing characterization and the background knowledge

**Comment by xiaoranzhou** [comment]
I will add: The project builds on existing data sets and relies on them. #if$_RNASEQ For instance, without a
                proper genomic reference it is very difficult to analyze NGS data sets. #endif$_RNASEQ It is also
                important to include existing data sets on the  <span class="list-to-remove-comma"> #if$_GENETIC genetic data, #endif$_GENETIC  
                #if$_GENOMIC genomic data, #endif$_GENOMIC 
                #if$_CLONED-DNA cloned DNA data, #endif$_CLONED-DNA 
                #if$_TRANSCRIPTOMIC transcriptomic data, #endif$_TRANSCRIPTOMIC  
                #if$_RNASEQ RNAseq data, #endif$_RNASEQ 
                #if$_METABOLOMIC Metabolomic data, #endif$_METABOLOMIC  
                #if$_PROTEOMIC proteomic data, #endif$_PROTEOMIC 
                #if$_PHENOTYPIC phenotypic data, #endif$_PHENOTYPIC  
                #if$_TARGETED targeted assays (e.g. glucose and fructose content), #endif$_TARGETED  
                #if$_IMAGE image datasets, #endif$_IMAGE  
                #if$_MODELS modelling data, #endif$_MODELS 
                #if$_CODE computational code, #endif$_CODE  
                #if$_EXCEL excel files #endif$_EXCEL </span> data of $_STUDYOBJECT,
                but of course, also on existing characterization and the background knowledge. #if$_PARTNERS of the
                partners: $_PARTNERS #endif$_PARTNERS Genomic references can simply be gathered from reference databases for
                genomes/sequences, like the National Center for Biotechnology Information: NCBI (US); European
                Bioinformatics Institute: EBI (EU); DNA Data Bank of Japan: DDBJ (JP). Furthermore, prior
                'unstructured' data in the form of publications and data contained therein will be used for decision
                making.

**Comment by StellaEggels** [comment]
How about:
The project builds on existing data sets. #if$_RNASEQ For instance, without a
proper genomic reference it is very difficult to analyze NGS data sets. #endif$_RNASEQ For, #if$_GENETIC genetic data, #endif$_GENETIC
#if$_GENOMIC genomic data, #endif$_GENOMIC
#if$_CLONED-DNA cloned DNA data, #endif$_CLONED-DNA
#if$_TRANSCRIPTOMIC transcriptomic data, #endif$_TRANSCRIPTOMIC
#if$_RNASEQ RNAseq data, #endif$_RNASEQ
#if$_METABOLOMIC Metabolomic data, #endif$_METABOLOMIC
#if$_PROTEOMIC proteomic data, #endif$_PROTEOMIC
#if$_PHENOTYPIC phenotypic data, #endif$_PHENOTYPIC
#if$_TARGETED targeted assays (e.g. glucose and fructose content), #endif$_TARGETED
#if$_IMAGE image datasets, #endif$_IMAGE
#if$_MODELS modelling data, #endif$_MODELS
#if$_CODE computational code, #endif$_CODE
#if$_EXCEL excel files #endif$_EXCEL data of $_STUDYOBJECT,
existing data sets as well as additional characterizations and background knowledge on the topic will be used from prior publications. #if$_PARTNERS of the
partners: $_PARTNERS #endif$_PARTNERS Genomic references can simply be gathered from reference databases for
genomes/sequences, like the National Center for Biotechnology Information: NCBI (US); European
Bioinformatics Institute: EBI (EU); DNA Data Bank of Japan: DDBJ (JP).
