### ISSUE TITLE
Sentence added in Section "Will you re-use any existing data and how?" is not understandable

### ISSUE THREAD

**Issue by AngelaKranz** [nfdi4plants/dataplan#54]
![image](https://github.com/user-attachments/assets/773ffd9e-a610-45ed-a653-9dbbfea91390)

This shows up, when I am selecting RNAseq or other NGS (genomics). If I do genomics, it might be that I actually do not have a reference genome.

Also, NGS data sets can be genomic data for genome assembly...

**Comment by xiaoranzhou** [comment]
Thank you very much for your time and effort to discover issues. I will keep the sentence "For instance, without a proper genomic reference it is very difficult to analyze NGS data sets." only show up for RNAseq.
