### ISSUE TITLE
Often you need to give project name AND acronym

### ISSUE THREAD

**Issue by AngelaKranz** [nfdi4plants/dataplan#59]
It does not make sense that you just can give one and then it is used for project name and acronym:

![image](https://github.com/user-attachments/assets/b71b6ab9-1685-42c1-b388-f2760151f567)

**Comment by xiaoranzhou** [comment]
I have added a acronym checkbox
![image](https://github.com/user-attachments/assets/c48d8dde-7b84-4ca2-9da4-089e726e2820)
