### ISSUE TITLE
RNAseq is not showing up when selected 

### ISSUE THREAD

**Issue by AngelaKranz** [nfdi4plants/dataplan#61]
![image](https://github.com/user-attachments/assets/fbe2f519-21e0-45ab-8417-afb2d395272e)

For other data types/repositories the text is showing up, but not for RNAseq.

**Comment by xiaoranzhou** [comment]
Thanks for your testing and feedback. I will categorize RNAseq as ENA. This is also one step forward to finish https://github.com/nfdi4plants/dataplan/issues/25 because I think once I have heard that some people believe ENA is only for genome data.
