### ISSUE TITLE
update DMP templates

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/dataplan#8]
- [ ] DFG template misses the very last question (6.3) "Who is responsible for curating the data once the project has ended?"
- [ ] H2020 has been replaced by Horizon Europe with own / updated DMP template (unfortunately I cannot find the link...)

**Comment by xiaoranzhou** [comment]
The Horizon Europe DMP is here. It is almost the same as H2020.
https://enspire.science/wp-content/uploads/2021/09/Horizon-Europe-Data-Management-Plan-Template.pdf

The DFG question is also added.
