### ISSUE TITLE
some notes from using the tool 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/dataplan#9]
- [ ] "genetic" twice in https://github.com/nfdi4plants/dataplan/blob/05f0ad344a009a063d8239fa9a9fb380f692cc89/index.html#L3683
- [ ] Sentence does not really make sense.  https://github.com/nfdi4plants/dataplan/blob/05f0ad344a009a063d8239fa9a9fb380f692cc89/index.html#L3236

- [ ] Not sure what "usually just a modern browser" refers to https://github.com/nfdi4plants/dataplan/blob/05f0ad344a009a063d8239fa9a9fb380f692cc89/index.html#L3368

- [ ] "RDM tools" instead of "DMP tools"? https://github.com/nfdi4plants/dataplan/blob/05f0ad344a009a063d8239fa9a9fb380f692cc89/index.html#L3782

- [ ]  which while not necessarily make the interaction with data more convenient
https://github.com/nfdi4plants/dataplan/blob/05f0ad344a009a063d8239fa9a9fb380f692cc89/index.html#L3374

- [ ] Sentence does not really make sense https://github.com/nfdi4plants/dataplan/blob/05f0ad344a009a063d8239fa9a9fb380f692cc89/index.html#L3522

**Comment by Brilator** [comment]
which while not necessarily make the interaction with data more convenient

https://github.com/nfdi4plants/dataplan/blob/05f0ad344a009a063d8239fa9a9fb380f692cc89/index.html#L3374

**Comment by xiaoranzhou** [comment]
> 

1st: there is no duplicated genetics. There is one genetics and one genomics.

Others are rephrased.

a "modern browser" can be found here : [search "modern browser" in google](https://www.google.com/search?q=%22modern+browser%22&rlz=1C1CHZN_enDE956DE956&sxsrf=ALiCzsZSFWwg6GKTzDZi-6NipbYcSXJoSA%3A1661961939281&ei=04YPY5jREJiG9u8Ps7qeuAo&ved=0ahUKEwjYhpXYuvH5AhUYg_0HHTOdB6cQ4dUDCA4&uact=5&oq=%22modern+browser%22&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEMsBMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgcIABBHELADOgcIABCwAxBDOgYIABAeEAdKBAhBGABKBAhGGABQhQhY9hFg9h5oAXABeACAAUiIAdkBkgEBNJgBAKABAcgBCsABAQ&sclient=gws-wiz
)

**Comment by Brilator** [comment]
> 1st: there is no duplicated genetics. There is one genetics and one genomics.

Just read one line further... 

https://github.com/nfdi4plants/dataplan/blob/05f0ad344a009a063d8239fa9a9fb380f692cc89/index.html#L3683

https://github.com/nfdi4plants/dataplan/blob/05f0ad344a009a063d8239fa9a9fb380f692cc89/index.html#L3684

**Comment by Brilator** [comment]
> a "modern browser" can be found here : [search "modern browser" in google](https://www.google.com/search?q=%22modern+browser%22&rlz=1C1CHZN_enDE956DE956&sxsrf=ALiCzsZSFWwg6GKTzDZi-6NipbYcSXJoSA%3A1661961939281&ei=04YPY5jREJiG9u8Ps7qeuAo&ved=0ahUKEwjYhpXYuvH5AhUYg_0HHTOdB6cQ4dUDCA4&uact=5&oq=%22modern+browser%22&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEMsBMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgcIABBHELADOgcIABCwAxBDOgYIABAeEAdKBAhBGABKBAhGGABQhQhY9hFg9h5oAXABeACAAUiIAdkBkgEBNJgBAKABAcgBCsABAQ&sclient=gws-wiz)

Sorry, are you trying to mock me?! I know what a modern browser is. 
I'm trying to help by reviewing your tool from perspective of a not data/code-affine person, who has never seen a DMP before and does not know your / DataPLANT's vision for what the platform and front-end could look like. 

But I'm happy to spend my time testing other tools. 
@BjoernUsadel @AngelaKranz

**Comment by xiaoranzhou** [comment]
> > a "modern browser" can be found here : [search "modern browser" in google](https://www.google.com/search?q=%22modern+browser%22&rlz=1C1CHZN_enDE956DE956&sxsrf=ALiCzsZSFWwg6GKTzDZi-6NipbYcSXJoSA%3A1661961939281&ei=04YPY5jREJiG9u8Ps7qeuAo&ved=0ahUKEwjYhpXYuvH5AhUYg_0HHTOdB6cQ4dUDCA4&uact=5&oq=%22modern+browser%22&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEMsBMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgcIABBHELADOgcIABCwAxBDOgYIABAeEAdKBAhBGABKBAhGGABQhQhY9hFg9h5oAXABeACAAUiIAdkBkgEBNJgBAKABAcgBCsABAQ&sclient=gws-wiz)
> 
> Sorry, are you trying to mock me?! I know what a modern browser is. I'm trying to help by reviewing your tool from perspective of a not data/code-affine person, who has never seen a DMP before and does not know your / DataPLANT's vision for what the platform and front-end could look like.
> 
> But I'm happy to spend my time testing other tools. @BjoernUsadel @AngelaKranz

I guess it is better to be less senstive to miscommunication? 
If you say "Not sure what <usually just a modern browser> refers to", I don't know if you want me to explain it to you, or you think it is better to add more context or add more explaination on this word. For me, the "modern browser" is not a niche word and can be found on google. We target user who can use computers and browsers.

**Comment by xiaoranzhou** [comment]
Closed bacuse no replies after more than two month

**Comment by Brilator** [comment]
Did you address the issues above?!

**Comment by xiaoranzhou** [comment]
> 
Dear @Brilator 
Thanks a lot for your quick  @reply. The text was rephrased and checked again in the past weeks. 
Your feedback is also considered in the rephrase. I did not see that the text errors persist. 
More feedback is welcome; I would be more grateful if you could give an example of the rephrased text. It would be even better if you could write an explanation of the concept that others might not understand.  

Best wishes,
Xiaoran
